{
  page(id: "/accueil", idType: URI) {
    id
    title
    content
    fields {
      postIt {
        title
        content
      }
      projects {
        nodes {
          id
          uri
          ... on Project {
            id
            title(format: RENDERED)
            featuredImage {
              node {
                altText
                sourceUrl
              }
            }
          }
        }
      }
    }
  }
}
