{
  projects(first: 100, where: { orderby: { field: DATE, order: DESC } }) {
    edges {
      node {
        id
        title
        slug
        uri
        featuredImage {
          node {
            altText
            sourceUrl(size: SMALL)
          }
        }
        fieldsProjectSidebar {
          annee
          lieu
          programme
          type
          statut
        }
        fieldsGallery {
          gallery(first: 100) {
            nodes {
              sourceUrl
            }
          }
        }
      }
    }
  }
}
