{
  page(id: "/projets", idType: URI) {
    id
    title
    content
    fields {
      projects {
        nodes {
          id
          uri
          ... on Project {
            id
            title(format: RENDERED)
          }
        }
      }
    }
  }
}
