{
  page(id: "/projects/", idType: URI) {
    id
    fieldsProjets {
      projects(first: 100) {
        nodes {
          id
          uri
          ... on Project {
            id
            title(format: RENDERED)
            fieldsProjectSidebar {
              lieu
              statut
              annee
            }
            featuredImage {
              node {
                altText
                sourceUrl(size: LARGE)
                mediaDetails {
                  width
                  height
                }
              }
            }
          }
        }
      }
    }
  }
}
