{
  page(id: "/", idType: URI) {
    id
    title
    content
    fieldsAccueil {
      postIt {
        title
        content
        lien
      }
      projects {
        nodes {
          id
          uri
          ... on Project {
            id
            title(format: RENDERED)
            featuredImage {
              node {
                altText
                sourceUrl(size: LARGE)
              }
            }
          }
        }
      }
    }
  }
}
