{
  page(id: "/projects/", idType: URI) {
    id
    title
    content
    fieldsProjets {
      projects {
        nodes {
          id
          uri
          ... on Project {
            id
            title(format: RENDERED)
            featuredImage {
              node {
                altText
                sourceUrl
              }
            }
          }
        }
      }
    }
  }
}
