{
  projects {
    edges {
      node {
        id
        title
        slug
        uri
        featuredImage {
          node {
            altText
            sourceUrl
          }
        }
        fieldsProjectSidebar {
          annee
          lieu
          programme
          type
          statut
        }
      }
    }
  }
}
