query getProject($slug: ID!) {
  project(id: $slug, idType: SLUG) {
    id
    slug
    title
    content: content(format: RENDERED)
    fieldsProjectSidebar {
      lieu
      ficheProjet {
        node {
          mediaItemUrl
        }
      }
    }
    featuredImage {
      node {
        altText
        sourceUrl(size: LARGE)
      }
    }
    fieldsGallery {
      gallery(first: 100) {
        nodes {
          altText
          sourceUrl(size: LARGE)
          mediaDetails {
            width
            height
          }
        }
      }
    }
  }
}
